version: "3.9"
services:
    db:
        hostname: bdsa-db
        ports:
            - "1433:1433"
        image: "mcr.microsoft.com/azure-sql-edge"
        environment:
            SA_PASSWORD: "SMBbdsaproject1"
            ACCEPT_EULA: "Y"