global using LibGit2Sharp;
global using System;
global using CommandLine;
global using Microsoft.EntityFrameworkCore;
global using System.Data.SqlClient;
global using System.Text;
global using GitInsight.Infrastructure;
global using Microsoft.Extensions.Configuration;
global using Microsoft.EntityFrameworkCore.Design;
global using Commit = GitInsight.Infrastructure.Commit;